#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: production-chefsteps
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test:guard"
    RAILS_ENV: "production"
    FOG_DIRECTORY: production-chefsteps-assets
    FOG_PROVIDER: AWS
    BUILDPACK_URL: https://github.com/ndbroadbent/heroku-buildpack-turbo-sprockets.git
  addons:
    - memcachier:dev
    - newrelic:standard
    - pgbackups:auto-month

staging:
  app: staging-chefsteps
  stack: cedar
  config: &default
    BUNDLE_WITHOUT: "development:test:guard"
    RAILS_ENV: "staging"
    FOG_DIRECTORY: staging-chefsteps-assets
    FOG_PROVIDER: AWS
    BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-ruby
  addons:
    - memcachier:dev
    - newrelic:standard
    - pgbackups:auto-month
